version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: craftmart-db
    environment:
      POSTGRES_DB: craftmart
      POSTGRES_USER: craftmart_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - craftmart-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: craftmart-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: craftmart
      DB_USER: craftmart_user
      DB_PASSWORD: your_secure_password
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - craftmart-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: craftmart-frontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - craftmart-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  craftmart-network:
    driver: bridge