# Cloudflare Tunnel Configuration (Token-based run)
# This config is used by `cloudflared tunnel run` with TUNNEL_TOKEN.
# No tunnel ID or credentials-file are required here.

ingress:
  # Route hostnames to nginx reverse proxy (serves frontend and proxies /api)
  - hostname: www.cmioe.com
    service: http://nginx:80
  - hostname: cmioe.com
    service: http://nginx:80

  # Catch-all rule (required as the last rule)
  - service: http_status:404

# Metrics endpoint (prometheus)
metrics: 0.0.0.0:2000

# Log level (debug, info, warn, error, fatal)
loglevel: info

# Prefer QUIC; Cloudflared will fall back to HTTP/2 automatically
protocol: quic
